name: Symfony CI & Secrets

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: human_be_ink
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3


    steps:
      - name: Checkout le code
        uses: actions/checkout@v3

      - name: Installer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Installer Composer
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Injecter les secrets dans .env.local
        run: |
          echo "APP_ENV=prod" >> .env.local
          echo "APP_SECRET=" >> .env.local
          echo "DATABASE_URL=mysql://root:root@127.0.0.1:3306/human_be_ink" >> .env.local
          echo "RECAPTCHA3_SECRET=${{ secrets.RECAPTCHA3_SECRET }}" >> .env.local
          echo "RECAPTCHA3_KEY=${{ secrets.RECAPTCHA3_KEY }}" >> .env.local

      - name: Vérifier que .env.local a été créé
        run: cat .env.local
        
      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h 127.0.0.1 -uroot -proot --silent; do
          echo "Waiting for MySQL..."
          sleep 5
          done

      - name: Compiler le cache Symfony
        run: php bin/console cache:clear --env=prod --no-debug
        
      - name: Appliquer les migrations
        run: php bin/console doctrine:migrations:migrate --no-interaction --env=prod
