name: Symfony CI & Secrets

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout le code
        uses: actions/checkout@v3

      - name: Installer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Installer Composer
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Injecter les secrets dans .env.local
        run: |
          echo "APP_ENV=prod" >> .env.local
          echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> .env.local
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env.local
          echo "RECAPTCHA3_SECRET=${{ secrets.RECAPTCHA3_SECRET }}" >> .env.local
          echo "RECAPTCHA3_KEY=${{ secrets.RECAPTCHA3_KEY }}" >> .env.local

      - name: Vérifier que .env.local a été créé
        run: cat .env.local

      - name: Compiler le cache Symfony
        run: php bin/console cache:clear --env=prod --no-debug

      - name: Appliquer les migrations
        run: php bin/console doctrine:migrations:migrate --no-interaction --env=prod
