name: Using GitHub Secrets

on: [push]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Add API key to env file
          env: 
            RECAPTCHA3_SECRET: ${{ secrets.RECAPTCHA3_SECRET }}
            RECAPTCHA3_KEY: ${{ secrets.RECAPTCHA3_KEY }}
          run: printf "\n\n
           RECAPTCHA3_SECRET=$RECAPTCHA3_SECRET\n
           RECAPTCHA3_KEY=$RECAPTCHA3_KEY" >> .env
        - name: afficher .env 
          run: cat .env
